<?php

namespace kamrul\Press;

use Illuminate\Support\ServiceProvider;

class PressBaseServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
